# Generated by Django 4.1.5 on 2023-02-15 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
